name: buoy_watch
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  sliding_up_panel: ^2.0.0
  intl: ^0.17.0
  firebase_core: ^2.32.0
  firebase_database: ^10.5.7
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  tflite_flutter: ^0.10.4 
  logging: ^1.0.2

# Dev dependencies are packages only needed during development or build process.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^3.0.0
  mockito: ^5.0.16
  build_runner: ^2.0.0
  firebase_core_platform_interface: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/Rectangle22.png
    - assets/Ellipse 6.png
    - assets/Ellipse 7.png
    - assets/Ellipse 8.png
    - assets/Group 21.png
    - assets/buoy.png
    - assets/model2.tflite
